### ISSUE TITLE
Add ability to include external markdown

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#429] opened 2019-07-30 01:24 UTC
it would be cool to be able to include markdown on the resource level, eg:

**footer.md**
```
some **footer** text.
```

**index.md**
```
# Welcome

Hello, world.

## Story

[embed](https://www.example.com/stories/1234.md)


[embed](/footer.md)
```

This could be useful for https://github.com/adobe/helix-home/issues/52

@trieloff WDYT?

/cc @davidnuescheler

**Comment by trieloff** [comment] 2019-07-30 10:11
Looks like a duplicate of #267 - the implementation in #270 does not use the same syntax you proposed, but is aligned with the most common embed syntaxes I've found. 

For `https://www.example.com/stories/1234.md` to work as an (external) embed, `example.com` would need to be added to a whitelist and `helix-embed` would need to know how to deal with files from that domain.

**Comment by tripodsan** [comment] 2019-07-31 04:22
ok, so this should already work with:

**index.md**
```
# Welcome

Hello, world.

## Story

`markdown:https://www.example.com/stories/1234.md`


`markdown:/footer.md`

```

**Comment by rofe** [comment] 2019-08-09 11:35
> ok, so this should already work (...)

In my [test](https://github.com/rofe/helixdemotest/blob/master/index.md), relative or absolute paths both result in an included 404.html, and a full URL gets printed as preformatted text.

**Comment by trieloff** [comment] 2019-08-09 17:13
I stand corrected: It should work if it wasn't buggy.

```markdown
/foo.md
```

results in:

```html
<esi:include src="/foo.embed.">
```

The `esi:include` is almost correct, it should be `/foo.embed.html`, which means there are two issues:

- [ ] the `html` ending somehow got dropped (might be a bug in dispatch or in pipeline or just an artifact of calling from Runtime)
- [ ] you and I don't have an `embed.html.htl` that creates an embed-friendly rendering (without headers and footers)

`https://adobeioruntime.net/api/v1/web/trieloff/helix-services/experimental-dispatch@v1static.owner=trieloff&static.repo=helix-demo&static.ref=master&static.root=/htdocs&content.owner=trieloff&content.repo=helix-demo&content.ref=master&content.root=&content.package=b7aa8a6351215b7e12b6d3be242c622410c1eb28&content.index=index.html&path=/more.html&strain=default&params=`

**Comment by ramboz** [comment] 2019-08-09 23:51
@trieloff Strange, I tried it locally on a plain CLI v4.9.11 and got it working as follows:

**1st approach**

`index.md`
```markdown
Foo

`markdown:/foo.md`
```

`foo.embed.html`
```html
<p>bar</p>
```

**2nd approach**

`index.md`
```markdown
`markdown:/foo.md`
```

`embed_html.htl`
```html
<p>${content.document.body.innerHTML @ context='unsafe'}</p>
```

`foo.md`
```markdown
baz
```

**Comment by trieloff** [comment] 2019-08-12 21:04
@ramboz I'd trace the actual ESI `src` URL generated and once that is correct, create the correct `embed_html.htl`

**Comment by kptdobe** [comment] 2019-08-28 13:55
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.

**Closed by kptdobe** 2019-08-28 13:55 UTC
Labels: enhancement
